### ISSUE TITLE
Max TPS Mixed mission fails due to bad upgrade

### ISSUE THREAD

**Issue by marta-lokhova** [stellar/supercluster#180]
Max TPS Mixed mission fails at random time due to 
```
[03:26:11 ERR] Exception thrown. Message = Loadgen failed! - StackTrace =   at StellarCoreHTTP.Peer.WaitForLoadGenComplete(Peer self, LoadGen loadGen) in /supercluster/src/FSLibrary/StellarCoreHTTP.fs:line 814
   at StellarStatefulSets.StellarFormation.RunLoadgen(StellarFormation self, CoreSet coreSet, LoadGen loadGen) in /supercluster/src/FSLibrary/StellarStatefulSets.fs:line 270
   at StellarStatefulSets.StellarFormation.SetupUpgradeContract(StellarFormation self, CoreSet coreSet) in /supercluster/src/FSLibrary/StellarStatefulSets.fs:line 278
   at MaxTPSTest.upgradeSorobanLedgerLimits(MissionContext context, StellarFormation formation, FSharpList`1 coreSetList, Int32 txrate) in /supercluster/src/FSLibrary/MaxTPSTest.fs:line 88
```

**Comment by bboston7** [comment]
Unfortunately this also affects the classic max TPS mission. We temporarily worked around it by disabling the check in #181. As part of resolving this issue we also need to re-enable the check.
