### ISSUE TITLE
SimulatePubnet is broken in k8s 1.22

### ISSUE THREAD

**Issue by SirTyson** [stellar/supercluster#90]
Following the recent upgrade to Kubernetes 1.22, the `SimulatePubnet` mission is broken. In particular, we get the following error around 7 minutes into every run:

```
[16:58:55 ERR] Exception thrown. Message = A task was canceled. - StackTrace =   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at k8s.Kubernetes.ReadNamespacedPodStatusWithHttpMessagesAsync(String name, String namespaceParameter, Nullable`1 pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.ReadNamespacedPodStatusAsync(IKubernetes operations, String name, String namespaceParameter, Nullable`1 pretty, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.ReadNamespacedPodStatus(IKubernetes operations, String name, String namespaceParameter, Nullable`1 pretty)
   at StellarDataDump.StellarFormation.LaunchLogTailingTasksForPod(StellarFormation self, PodName podName) in /home/user/src/supercluster/src/FSLibrary/StellarDataDump.fs:line 71
   at StellarDataDump.StellarFormation.LaunchLogTailingTasksForCoreSet(StellarFormation self, CoreSet cs) in /home/user/src/supercluster/src/FSLibrary/StellarDataDump.fs:line 95
   at StellarStatefulSets.StellarFormation.WaitForAllReplicasReady(StellarFormation self, V1StatefulSet ss) in /home/user/src/supercluster/src/FSLibrary/StellarStatefulSets.fs:line 80
   at StellarStatefulSets.StellarFormation.WaitForAllReplicasOnAllSetsReady(StellarFormation ) in /home/user/src/supercluster/src/FSLibrary/StellarStatefulSets.fs:line 90
   at StellarSupercluster.Kubernetes.MakeFormation(Kubernetes self, NetworkCfg nCfg) in /home/user/src/supercluster/src/FSLibrary/StellarSupercluster.fs:line 160
   at StellarSupercluster.MissionContext.MakeFormation(MissionContext self, FSharpList`1 coreSetList, FSharpOption`1 passphrase) in /home/user/src/supercluster/src/FSLibrary/StellarSupercluster.fs:line 215
   at StellarSupercluster.MissionContext.ExecuteWithOptionalConsistencyCheck(MissionContext self, FSharpList`1 coreSetList, FSharpOption`1 passphrase, Boolean checkConsistency, FSharpFunc`2 run) in /home/user/src/supercluster/src/FSLibrary/StellarSupercluster.fs:line 248
   at StellarSupercluster.MissionContext.Execute(MissionContext self, FSharpList`1 coreSetList, FSharpOption`1 passphrase, FSharpFunc`2 run) in /home/user/src/supercluster/src/FSLibrary/StellarSupercluster.fs:line 266
   at MissionSimulatePubnet.simulatePubnet(MissionContext context) in /home/user/src/supercluster/src/FSLibrary/MissionSimulatePubnet.fs:line 70
   at StellarMission.allMissions@78-32.Invoke(MissionContext context) in /home/user/src/supercluster/src/FSLibrary/StellarMission.fs:line 78
   at Program.main(String[] argv) in /home/user/src/supercluster/src/App/Program.fs:line 510
Unhandled exception. System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at k8s.Kubernetes.ReadNamespacedPodStatusWithHttpMessagesAsync(String name, String namespaceParameter, Nullable`1 pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.ReadNamespacedPodStatusAsync(IKubernetes operations, String name, String namespaceParameter, Nullable`1 pretty, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.ReadNamespacedPodStatus(IKubernetes operations, String name, String namespaceParameter, Nullable`1 pretty)
   at StellarDataDump.StellarFormation.LaunchLogTailingTasksForPod(StellarFormation self, PodName podName) in /home/user/src/supercluster/src/FSLibrary/StellarDataDump.fs:line 71
   at StellarDataDump.StellarFormation.LaunchLogTailingTasksForCoreSet(StellarFormation self, CoreSet cs) in /home/user/src/supercluster/src/FSLibrary/StellarDataDump.fs:line 95
   at StellarStatefulSets.StellarFormation.WaitForAllReplicasReady(StellarFormation self, V1StatefulSet ss) in /home/user/src/supercluster/src/FSLibrary/StellarStatefulSets.fs:line 80
   at StellarStatefulSets.StellarFormation.WaitForAllReplicasOnAllSetsReady(StellarFormation ) in /home/user/src/supercluster/src/FSLibrary/StellarStatefulSets.fs:line 90
   at StellarSupercluster.Kubernetes.MakeFormation(Kubernetes self, NetworkCfg nCfg) in /home/user/src/supercluster/src/FSLibrary/StellarSupercluster.fs:line 160
   at StellarSupercluster.MissionContext.MakeFormation(MissionContext self, FSharpList`1 coreSetList, FSharpOption`1 passphrase) in /home/user/src/supercluster/src/FSLibrary/StellarSupercluster.fs:line 215
   at StellarSupercluster.MissionContext.ExecuteWithOptionalConsistencyCheck(MissionContext self, FSharpList`1 coreSetList, FSharpOption`1 passphrase, Boolean checkConsistency, FSharpFunc`2 run) in /home/user/src/supercluster/src/FSLibrary/StellarSupercluster.fs:line 248
   at StellarSupercluster.MissionContext.Execute(MissionContext self, FSharpList`1 coreSetList, FSharpOption`1 passphrase, FSharpFunc`2 run) in /home/user/src/supercluster/src/FSLibrary/StellarSupercluster.fs:line 266
   at MissionSimulatePubnet.simulatePubnet(MissionContext context) in /home/user/src/supercluster/src/FSLibrary/MissionSimulatePubnet.fs:line 70
   at StellarMission.allMissions@78-32.Invoke(MissionContext context) in /home/user/src/supercluster/src/FSLibrary/StellarMission.fs:line 78
   at Program.main(String[] argv) in /home/user/src/supercluster/src/App/Program.fs:line 510
```

This error appears to be a network timeout, where the request for the pod's status times out. Initially, we suspected it could be due to internal liveness probe bugs outlined [here](https://github.com/kubernetes/kubernetes/issues/88555), but after switching away from the HTTP GET request probe to a curl based probe, we still see the error. Additionally, the error is not a race condition, but is reproduceable. On back to back runs, a status check for the same pod fails with the same error above. We also tried reading the pod status in a loop, retrying after each failure. Every attempt failed, meaning it is unlikely to be a load based issue as outlined in the kubernetes' repo issue.

We see the failure when attempting to read the status of `ssc-2353z-73f60f-sts-publicnode-2`. Interestingly, reading the status of the other pods in the stateful set succeeds, `ssc-2353z-73f60f-sts-publicnode-0` and `ssc-2353z-73f60f-sts-publicnode-1`. Below, I have attached the YAML files for the stateful set, the failed pod, and another pod in the stateful set that succeeded. I have also attached the descriptions on the stateful set and pods (i.e. the output is `kubectl describe`).

[bug-files.zip](https://github.com/stellar/supercluster/files/11206017/bug-files.zip)

**Comment by marta-lokhova** [comment]
Resolved via https://github.com/stellar/supercluster/pull/135, closing
